
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: k8ssecondtry
  labels:
    group: trial
spec: # specification of the pod 
  replicas: 1
  selector: # identifies which other services needs to be controlled 
    matchLabels:
      app: k8ssecondtrial 
      tier: backend
    # matchExpression:
    #   app: 
  template:
    metadata:
      labels:  
        app: k8ssecondtrial
        tier: backend
    spec: # specification of the containers in the pod
      containers:
        - name: k8ssecondtrialcon1
          image: mohamedaklamaash/kub8try1:latest
          # imagePullPolicy: Always
          livenessProbe: # can be used to check healthness of the app
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
