apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: trial
spec:
  selector:
    app: k8ssecondtrial
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 8080 # port that app uses to run
  type: LoadBalancer