apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
        - name: frontendcontainer
          image: mohamedaklamaash/k8snetworksfrontend:v1
          imagePullPolicy: Always

