apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskbackendapi
  template:
    metadata:
      labels:
        app: taskbackendapi
    spec:
      containers:
        - name: taskapicontainer
          image: mohamedaklamaash/k8snetworkstasksapi:v1
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              # value: localhost
              # value: "Ip address can be hardcoded"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks