version: '3.8'

services:
  server:
    image: 'nginx:1.24.0-alpine-slim'
    ports:
      - '8000:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
  php:
    build: 
      context: ./php_dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  sql:
    image: mysql
    env_file:
      - './env/mysql.env'
  composer:
    build: 
      context: ./php_dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
