apiVersion: v1
kind: PersistentVolume
metadata: 
  name: hostpv 
spec: 
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem #Block is also a volume mode
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
